### ISSUE TITLE
Creation of the virutal environment on windows

### ISSUE THREAD

**Issue by BorgeatRemy** [swiss-ai-center/documentation#113]
This is incorrect when developping under Windows :

https://github.com/swiss-ai-center/documentation/blob/539b6b96843451e623de389554ef73309e373d3f/docs/tutorials/create-a-service-to-rotate-an-image.md?plain=1#L109C1-L114C4

On windows the virtual environment needs to be started as follow :
`.\venv\Scripts\activate`. 

Once the environment created, we can install the requirments.txt and generate the requirments-all.txt (same way as linux). 

Once done, Virtual environment needs to be deleted. 

Finally, the docker-compose can be launched.

**Comment by andrptrc** [comment]
@rmarquis Can you check this on your Windows machine ?
