### ISSUE TITLE
Repo configuration

### ISSUE THREAD

**Issue by BorgeatRemy** [swiss-ai-center/documentation#114]
Most of these configuration are not available on the current github version. 

https://github.com/swiss-ai-center/documentation/blob/539b6b96843451e623de389554ef73309e373d3f/docs/how-to-guides/how-to-configure-a-new-github-repository.md?plain=1#L69C1-L82C55

**Comment by rmarquis** [comment]
I can actually see these options (in Settings > Branches). What is actually incorrect?

**Comment by BorgeatRemy** [comment]
I finally find where these were, my bad :  You have to go in Settings --> Branches --> Add classic branch protection rules

**Comment by andrptrc** [comment]
Can we close this issue then ? @BorgeatRemy
