### ISSUE TITLE
Create the 'how-to-guides/how-to-create-and-configure-a-new-github-repository.md' guide

### ISSUE THREAD

**Issue by andrptrc** [swiss-ai-center/documentation#38]
In mkdocs logs, this relative link appears but the How to guide doesn't exist yet.

**Comment by ludelafo** [comment]
I have written the guide last week here: <https://github.com/swiss-ai-center/documentation/blob/main/docs/how-to-guides/how-to-configure-a-new-github-repository.md>. I guess the link is simply wrong but everything is already there.

**Comment by andrptrc** [comment]
Perfect will fix it in my next PR

**Comment by ludelafo** [comment]
Online link available here: <https://docs.swiss-ai-center.ch/how-to-guides/how-to-configure-a-new-github-repository/>

**Comment by andrptrc** [comment]
Corrected in #39
